name: Generate Documentation

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: |
          doxygen -g Doxyfile
          doxygen Doxyfile

      - name: Deploy Documentation
        run: |
          mkdir docs
          mkdir docs/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr create --title "Update Documentation" --body "Automated documentation update" --base main --head ${{ github.sha }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
