name: Generate Documentation

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: |
          doxygen -g Doxyfile
          doxygen Doxyfile

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html  # Replace with the directory where your generated documentation is located
